export const HEADERS_COLUMN = [
  { dbName: "name", name: "Тикер", up: false, w: "112px" },
  { dbName: "resultId", name: "Win-Loss", up: true, w: "105px" },
  { dbName: "lsId", name: "ls", up: true, w: "96px" },
  { dbName: "pose", name: "Поза", up: false, w: "96px" },
  { dbName: "risk", name: "Риск", up: false, w: "80px" },
  { dbName: "profit", name: "Профит", up: false, w: "80px" },
  // { dbName: "forecast", name: "Прогноз", up: false, w: "96px" },
  { dbName: "entrieTake", name: "Тейки", up: false, w: "124px" },
  // { dbName: "rrId", name: "R:R", up: true, w: "80px" },
  { dbName: "entryDate", name: "Вход", up: true, w: "144px" },
  { dbName: "imageStart", name: "Скрин", up: true, w: "96px" },
  { dbName: "deposit", name: "Депозит", up: true, w: "112px" },
  { dbName: "progress", name: "Прогресс", up: true, w: "112px" },
  { dbName: "exitDate", name: "Выход", up: true, w: "144px" },
  { dbName: "imageEnd", name: "Скрин2", up: true, w: "96px" },
  { dbName: "take", name: "Пора?", up: false, w: "112px" },
  { dbName: "stress", name: "Стресс", up: true, w: "96px" },
  { dbName: "entrieTag", name: "Tags", up: false, w: "288px" },
  { dbName: "notes", name: "Заметки", up: false, w: "176px" },
  { dbName: "timeInTrade", name: "Время в сделке", up: true, w: "128px" },
];

export const COLUMN_WIDTH = {
  name: "112px",
  resultId: "105px",
  lsId: "96px",
  pose: "96px",
  risk: "80px",
  profit: "80px",
  // forecast: "96px",
  entrieTake: "124px",
  // rrId: "80px",
  entryDate: "144px",
  imageStart: "96px",
  deposit: "112px",
  progress: "112px",
  exitDate: "144px",
  imageEnd: "96px",
  take: "112px",
  stress: "96px",
  entrieTag: "288px",
  notes: "176px",
  timeInTrade: "128px",
};

export const ITEMS = [
  { id: "name", label: "Тикер" },
  { id: "resultId", label: "Win-Loss" },
  { id: "lsId", label: "LS" },
  { id: "pose", label: "Поза" },
  { id: "risk", label: "Риск" },
  { id: "profit", label: "Профит" },
  // { id: "forecast", label: "Прогноз" },
  { id: "entrieTake", label: "Тейки" },
  // { id: "rrId", label: "R:R" },
  { id: "entryDate", label: "Вход" },
  { id: "imageStart", label: "СКРИН" },
  { id: "deposit", label: "Депозит" },
  { id: "progress", label: "Прогресс" },
  { id: "exitDate", label: "Выход" },
  { id: "imageEnd", label: "СКРИН 2" },
  { id: "take", label: "Пора?" },
  { id: "stress", label: "Стресс" },
  { id: "entrieTag", label: "Теги" },
  { id: "notes", label: "Заметки" },
  { id: "timeInTrade", label: "Время в сделке" },
];

export const PAGE_SIZE_STAT_TIKER = 8;
export const PAGE_SIZE_STAT_HOURS = 8;

export const DAYS = [
  "Воскресенье",
  "Понедельник",
  "Вторник",
  "Среда",
  "Четверг",
  "Пятница",
  "Суббота",
];
