export const HEADERS_COLUMN = [
    { dbName: "name", name: "Тикер", up: false, w: "112px" },
    { dbName: "resultId", name: "Win-Loss", up: true, w: "96px" },
    { dbName: "lsId", name: "ls", up: true, w: "96px" },
    { dbName: "pose", name: "Поза", up: false, w: "96px" },
    { dbName: "risk", name: "Риск", up: false, w: "70px" },
    { dbName: "profit", name: "Профит", up: false, w: "80px" },
    { dbName: "rrId", name: "R:R", up: true, w: "80px" },
    { dbName: "entryDate", name: "Вход", up: true, w: "144px" },
    { dbName: "imageStart", name: "Скрин", up: true, w: "96px" },
    { dbName: "deposit", name: "Депозит", up: true, w: "112px" },
    { dbName: "progress", name: "Прогресс", up: true, w: "112px" },
    { dbName: "exitDate", name: "Выход", up: true, w: "144px" },
    { dbName: "imageEnd", name: "Скрин2", up: true, w: "96px" },
    { dbName: "take", name: "Пора?", up: false, w: "112px" },
    { dbName: "stress", name: "Стресс", up: true, w: "96px" },
    { dbName: "entrieTag", name: "Tags", up: false, w: "288px" },
    { dbName: "notes", name: "Заметки", up: false, w: "176px" },
    { dbName: "timeInTrade", name: "Время в сделке", up: true, w: "128px" },
];

export const COLUMN_WIDTH = {
    column1: "112px",
    column2: "105px",
    column3: "96px",
    column4: "96px",
    column5: "70px",
    column6: "80px",
    column7: "80px",
    column8: "144px",
    column9: "96px",
    column10: "112px",
    column11: "112px",
    column12: "144px",
    column13: "96px",
    column14: "112px",
    column15: "96px",
    column16: "288px",
    column17: "176px",
    column18: "128px",
};
