export const ITEMS = [
    { id: "name", label: "Тикер" },
    { id: "resultId", label: "win-loss" },
    { id: "lsId", label: "long-short" },
    { id: "pose", label: "Поза" },
    { id: "risk", label: "Риск" },
    { id: "profit", label: "Профит" },
    { id: "rrId", label: "R:R" },
    { id: "entryDate", label: "Вход" },
    { id: "imageStart", label: "СКРИН" },
    { id: "deposit", label: "Депозит" },
    { id: "progress", label: "Прогресс" },
    { id: "exitDate", label: "Выход" },
    { id: "imageEnd", label: "Скрин 2" },
    { id: "take", label: "Пора?" },
    { id: "stress", label: "Стресс" },
    { id: "entrieTag", label: "Теги" },
    { id: "notes", label: "Заметки" },
    { id: "timeInTrade", label: "Время в сделке" },
];
